name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  terraform-checks:
    uses: shoekstra/terraform-workflows/.github/workflows/pr-checks.yaml@master
    secrets: inherit
