name: Release Please

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: shoekstra/terraform-workflows/.github/workflows/release.yaml@master
    secrets: inherit
